export const languageIconMap: Record<string, string> = {
  javascript: "SiJavascript",
  typescript: "SiTypescript",
  python: "SiPython",
  ruby: "SiRuby",
  go: "SiGo",
  rust: "SiRust",
  php: "SiPhp",
  c: "SiC",
  cpp: "SiCplusplus",
  csharp: "SiSharp",
  html: "SiHtml5",
  css: "SiCss3",
  shell: "SiGnubash",
  swift: "SiSwift",
  kotlin: "SiKotlin",
  dart: "SiDart",
  scala: "SiScala",
  perl: "SiPerl",
  r: "SiR",
};
